#!/bin/sh

while true
do

    battery()
    {
        STATCHAR="[$(cat /sys/class/power_supply/BAT1/status | colrm 2 99)]"

    # When battery is completely charged, Plug icon will be shown indicating
    # power from AC supply. If not, then "D" or "C" depending on it's
    # status.
        [ "$STATCHAR" = "[F]" ] && echo -n "" && return 0

        CAP="$(cat /sys/class/power_supply/BAT1/capacity)%"

        echo -n " $CAP $STATCHAR"
    }

    vol()
    {
        echo -n " $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
    }

    cpu()
    {
        echo -n " $(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
    }

    ram()
    {
        FREE_DATA=$(free -m | grep Mem)
        CURRENT=$(echo $FREE_DATA | cut -f3 -d' ')
        TOTAL=$(echo $FREE_DATA | cut -f2 -d' ')

        echo -n " $(echo "scale = 1; ($CURRENT/$TOTAL)*100" | bc)%"
    }

    temp()
    {
        echo -n " $(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)"
    }

    datetime()
    {
        echo -n " $(date +'%a'), $(date +'%b %d')  $(date +'%H:%M')"
    }

     bandwidth()
    {
        # i3bar script.
        # TODO: Remove dependancy on this script.
        echo -n "$(/usr/share/i3blocks/bandwidth)"
    }



xsetroot -name "$(vol)  |  $(battery)  |  $(ram)  »  $(cpu)  «  $(temp)  |  $(datetime)"
# xsetroot -name "$(bandwidth)  |  $(vol)  |  $(battery)  |  $(ram)  »  $(cpu)  «  $(temp)  |  $(datetime)"
    sleep 2s

done &
