#!/bin/sh

while true
do

    lockind()
    {
        CAPSLOCK="$(xset q | grep 'Caps Lock' |sed 's/.*Caps Lock: *\([a-z]\{2,3\}\).*/\1/')"
        NUMLOCK="$(xset q | grep 'Caps Lock' |sed 's/.*Num Lock: *\([a-z]\{2,3\}\).*/\1/')"
        [ "$CAPSLOCK" = "off" ] && CAPSLOCK="a" || CAPSLOCK="A"
        [ "$NUMLOCK" = "off" ] && NUMLOCK="-" || NUMLOCK=""
        echo -n "$CAPSLOCK  $NUMLOCK"
    }

    battery()
    {
        STATCHAR="[$(cat /sys/class/power_supply/BAT1/status | colrm 2 99)]"

    # When battery is completely charged, Plug icon will be shown indicating
    # power from AC supply. If not, then "D" or "C" depending on it's
    # status.
        [ "$STATCHAR" = "[F]" ] && echo -n "" && return 0

        CAP="$(cat /sys/class/power_supply/BAT1/capacity)%"

        echo -n " $CAP $STATCHAR"
    }

    vol()
    {
        amixer get Master | tail -1 | grep -w "on" >/dev/null &&
        echo -n " $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')" ||
        echo -n " MUTE"
    }

    cpu()
    {
        echo -n " $(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
    }

    ram()
    {
        FREE_DATA=$(free -m | grep Mem)
        CURRENT=$(echo $FREE_DATA | cut -f3 -d' ')
        TOTAL=$(echo $FREE_DATA | cut -f2 -d' ')

        echo -n " $(echo "scale = 1; ($CURRENT/$TOTAL)*100" | bc)%"
    }

    temp()
    {
        echo -n " $(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)"
    }

    datetime()
    {
        echo -n " $(date +'%a'), $(date +'%b %d')  $(date +'%H:%M')"
    }

     bandwidth()
    {
        # i3bar script.
        $HOME/.scripts/i3blocks/custom/bandwidth
    }


xsetroot -name "$(bandwidth)  |  $(vol)  |  $(battery)  |  $(ram)    $(cpu)    $(temp)  |  $(datetime)  |  $(lockind)"
    sleep 2s

done &
