#!/bin/bash

while true
do

    battery()
    {
        STATUS="$(cat /sys/class/power_supply/BAT1/status)"

    # When battery is completely charged, Plug icon will be shown indicating
    # power from AC supply. If not, then "(D)" or "(C)" depending on it's
    # status.
        [ "$STATUS" = "Full" ] && echo -n "" && return 0
        [ "$STATUS" = "Unknown" ] && echo -n "" && return 0
        { [ "$STATUS" = "Charging" ] && STATCHAR="(C)"; } ||
            { [ "$STATUS" = "Discharging" ] && STATCHAR="(D)"; }

        CAP="$(cat /sys/class/power_supply/BAT1/capacity)%"

        echo -n " $CAP $STATCHAR"
    }

    vol()
    {
        echo -n " $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
    }

    cpu()
    {
        echo -n " $(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
    }

    ram()
    {
        FREE_DATA=$(free -m | grep Mem)
        CURRENT=$(echo $FREE_DATA | cut -f3 -d' ')
        TOTAL=$(echo $FREE_DATA | cut -f2 -d' ')

        echo -n " $(echo "scale = 2; ($CURRENT/$TOTAL)*100" | bc)%"
    }

    temp()
    {
        echo -n " $(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)"
    }

    datetime()
    {
        echo -n " $(date +'%a'), $(date +'%b %d')  $(date +'%H:%M')"
    }

#     bandwidth()
#    {
#
#    }



    xsetroot -name "$(battery)  |  $(vol)  |  $(ram)  »  $(cpu)  «  $(temp)  |  $(datetime)"
    sleep 2s

done &
