#!/bin/bash

while true
do
	# BANDWIDTH=

	BAT="BAT $(cat /sys/class/power_supply/BAT1/capacity)%"

	VOL="VOL $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"

	# CPUUSAGE="CPU )"

	TEMP="$(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)"

	# up or down.
	WIFISTAT="$(cat /sys/class/net/wlp3s0/operstate)"

	TIME="$(date +'%a'), $(date +'%b %d')  $(date +'%H:%M')"



	xsetroot -name "$BAT    $VOL    $TEMP    $WIFISTAT    $TIME"
	sleep 2s
done &
