#!/bin/sh

# Always run this script relative to current path (eg: `. gadd`). Or else
# `cd` will not actually change directory!

cd $HOME/pnl/github/dot-files/T480/

git checkout T480 >/dev/null

# Remove all hidden files.
rm -rf $HOME/pnl/github/dot-files/T480/.[A-z]*

# Remove all files in "scripts" submodule.
rm -rf $HOME/pnl/github/dot-files/T480/scripts/*

cp -fr                  \
$HOME/.scripts/*        \
$HOME/pnl/github/dot-files/scripts

# Changed files at $HOME/.
cp -fr              \
$HOME/.vim          \
$HOME/.bash         \
$HOME/.fonts        \
$HOME/.alias        \
$HOME/.vimrc        \
$HOME/.bashrc       \
$HOME/.inputrc      \
$HOME/.profile      \
$HOME/.gitconfig    \
$HOME/.Xresources   \
$HOME/.bash_profile \
$HOME/pnl/github/dot-files/T480/

# Changed files in $HOME/.config/.
mkdir -p $HOME/pnl/github/dot-files/T480/.config/
cp -fr                      \
$HOME/.config/i3            \
$HOME/.config/dunst         \
$HOME/.config/compton       \
$HOME/.config/gsimplecal    \
$HOME/pnl/github/dot-files/T480/.config/

git status
