#!/bin/sh

# Always source this script, do not execute or else
# `cd` will not actually change directory!

cd $HOME/pnl/github/dot-files/

git checkout T480 >/dev/null

# Remove all hidden files.
rm -rf $HOME/pnl/github/dot-files/T480/.[A-z]*

# Remove all files in "scripts" submodule.
rm -rf $HOME/pnl/github/dot-files/scripts/*

mkdir -p $HOME/pnl/github/dot-files/T480/.local/share

cp -fr                      \
$HOME/.scripts/*            \
$HOME/pnl/github/dot-files/scripts
# Changed files at $HOME/.
cp -fr                      \
$HOME/.vim                  \
$HOME/.bash                 \
$HOME/.fonts                \
$HOME/.alias                \
$HOME/.vimrc                \
$HOME/.bashrc               \
$HOME/.inputrc              \
$HOME/.profile              \
$HOME/.gitconfig            \
$HOME/.Xresources           \
$HOME/.bash_profile         \
$HOME/.local/share/konsole  \
$HOME/pnl/github/dot-files/T480/

# Changed files in $HOME/.config/.
mkdir -p $HOME/pnl/github/dot-files/T480/.config/
cp -fr                      \
$HOME/.config/i3            \
$HOME/.config/dunst         \
$HOME/.config/compton       \
$HOME/.config/gsimplecal    \
$HOME/pnl/github/dot-files/T480/.config/

git status
