#!/bin/sh

# Always source this script, do not execute or else
# `cd` will not actually change directory!

cd $HOME/pnl/github/dot-files/

git checkout T480 >/dev/null

# Remove all files in T480/.
rm -rf $HOME/pnl/github/dot-files/T480

# Create longest directory so that all parent directories will be auto-created.
mkdir -p $HOME/pnl/github/dot-files/T480/

# Copy changed files at $HOME/.
cp -fr                      \
$HOME/.vim                  \
$HOME/.bash                 \
$HOME/.fonts                \
$HOME/.alias                \
$HOME/.vimrc                \
$HOME/.bashrc               \
$HOME/.inputrc              \
$HOME/.profile              \
$HOME/.gitconfig            \
$HOME/.Xresources           \
$HOME/.bash_profile         \
$HOME/pnl/github/dot-files/T480/

# Copy files at $HOME/.local/share.
mkdir -p $HOME/pnl/github/dot-files/T480/.local/share
cp -rf                          \
$HOME/.local/share/konsole      \
$HOME/.local/share/supplements  \
$HOME/pnl/github/dot-files/T480/.local/share

# Copy changed files at $HOME/.config/.
mkdir -p $HOME/pnl/github/dot-files/T480/.config/
cp -fr                      \
$HOME/.config/i3            \
$HOME/.config/dunst         \
$HOME/.config/compton       \
$HOME/.config/picom         \
$HOME/.config/gsimplecal    \
$HOME/.config/fontconfig    \
$HOME/pnl/github/dot-files/T480/.config/

echo "dot-files status:"
git status

# For scripts

echo "Switching to scripts"

# Keep a single copy of git specific files like README by saving them and
# retrieving them later after deleting.
mkdir -p /tmp/scriptFiles/

mv $HOME/pnl/github/scripts/README.md         \
$HOME/pnl/github/scripts/img_blur_lock.png    \
$HOME/pnl/github/scripts/requirements.txt     \
/tmp/scriptFiles/

# Remove all files in "scripts" repo.
rm -rf $HOME/pnl/github/scripts/*

mv /tmp/scriptFiles/*   \
$HOME/pnl/github/scripts/

cp -fr                      \
$HOME/.scripts/*            \
$HOME/pnl/github/scripts

rm -rf /tmp/scriptFiles/

cd $HOME/pnl/github/scripts/
echo "scripts status:"
git status
