#!/bin/bash

echo $(date) > $HOME/downspeed
echo '' >> $HOME/downspeed
for((i=0;i<10;i++));do
    (command -v speedtest >/dev/null && speedtest --no-upload |grep ^Download |tee -a $HOME/downspeed) || echo "Error"
done

# Give any argument for logging upload speed also.
if [ $# -ne 0 ]; then
    echo $(date) > $HOME/upspeed
echo '' >> $HOME/upspeed
    for((i=0;i<10;i++));do
        command -v speedtest >/dev/null && speedtest --no-download |grep ^Upload |tee -a $HOME/upspeed
    done
fi
